# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Fri, 04 Aug 2023 23:08:06 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

dragonnova:$2y$10$8bQqeXIUOTG7DFqJorzHUe93zCbJEEZPTJh6yDzIRfPs9bzdCsski:Ethan Hunter:dragonnova5091@gmail.com:admin,user
